team-ppointer/pointer_server

- src/main/java/com/moplus/moplus_server/domain/auth/controller/AuthController.java
- src/main/java/com/moplus/moplus_server/domain/member/service/MemberService.java
- src/main/java/com/moplus/moplus_server/global/config/security/SecurityConfig.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
- src/main/java/com/moplus/moplus_server/global/security/exception/JwtInvalidException.java
- src/main/java/com/moplus/moplus_server/global/security/filter/JwtAuthenticationFilter.java
- src/main/java/com/moplus/moplus_server/global/security/handler/EmailPasswordSuccessHandler.java
- src/main/java/com/moplus/moplus_server/global/security/provider/JwtTokenProvider.java
- src/main/java/com/moplus/moplus_server/global/security/token/JwtAuthenticationToken.java
- src/main/java/com/moplus/moplus_server/global/security/utils/JwtUtil.java
- src/test/java/com/moplus/moplus_server/global/security/utils/JwtUtilTest.java
- close #11 
- 저번에 구현한 이메일 패스워드 인증 후 인증 상태 유지를 위해 JwtAuthenticationFilter를 spring security에 추가하였습니다.
- <img width="1564" alt="image" src="https://github.com/user-attachments/assets/fb4a1fc8-e174-469d-9eac-eb80f3aa155a" />
- 빨간 색으로 표시한 부분이 추가 필터 로직입니다.
- 저번에 구성하였던 AuthenticationManger에 AuthenticationProvider를 구현한 JwtTokenProvider를 추가하여 여러개의 인증 Provider 관리 책임은 Manger가 하도록 유지했습니다.
- Jwt를 인증하는 책임은 JwtTokenProvider가 맡습니다.
- Filter의 순서는 JwtAuthenticationFilter -> EmailPasswordAuthenticationFilter 순 입니다. 토큰이 없을 시 다음 이메일 패스워드 필터로 넘어가는 순서입니다. 아무 인증도 없을 시 예외가 발생하고 authenticationEntryPoint가 공통적으로 처리합니다.
- jwt유효성 검사가 잘 이우러지는지 테스트를 추가했습니다.
- 기존 로그인 방식의 인증 통합 테스트도 잘 이루어지는 것을 볼 수 있습니다.
- JwtAuthenticationFilter를 추가하며 기존 로그인 통합테스트가 실패했었습니다.
- 원인1 : spring security 6.x.x 버전으로 올라오면서 AuthenticationManger …
> [feat/#11] jwt 인증 필터 구현

- src/main/java/com/moplus/moplus_server/domain/DetailResultApplication/controller/DetailResultApplicationController.java
- src/main/java/com/moplus/moplus_server/domain/TestResult/controller/RatingController.java
- src/main/java/com/moplus/moplus_server/domain/TestResult/controller/TestResultController.java
- src/main/java/com/moplus/moplus_server/domain/practiceTest/api/admin/PracticeTestAdminController.java
- src/main/java/com/moplus/moplus_server/domain/practiceTest/api/admin/PracticeTestCreateController.java
- src/main/java/com/moplus/moplus_server/domain/practiceTest/api/admin/ProblemAdminController.java
- src/main/java/com/moplus/moplus_server/domain/practiceTest/api/admin/ProblemImageUploadController.java
- src/main/java/com/moplus/moplus_server/domain/practiceTest/api/client/PracticeTestController.java
- close #15 
- 사용하지 않는 이전 API를 swagger에서 뜨지 않게 수정하였습니다.
- 쓰지 않는 Controller에 @Hidden 을 달아주었습니다.
- 해당 pr #11 브랜치 위에서 작업되었습니다. #11 을 먼저 리뷰해주세요
> [docs/#15] 사용하지 않는 api swagger에서 정리

- src/main/java/com/moplus/moplus_server/domain/concept/domain/ConceptTag.java
- src/main/java/com/moplus/moplus_server/domain/concept/repository/ConceptTagRepository.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/ChildProblem.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/Problem.java
- src/main/java/com/moplus/moplus_server/domain/problem/repository/ChildProblemRepository.java
- src/main/java/com/moplus/moplus_server/domain/problem/repository/ProblemRepository.java
- close #21 
---
- **문항**, **새끼 문항**, **개념 태그**를 각각 독립적인 **애그리거트**로 구성하였습니다.
- 초기에는 문항과 새끼 문항을 하나의 애그리거트로 간주했으나, 출제진의 문제 업로드 과정을 분석한 결과, 두 엔티티의 생명주기가 다르다는 점을 확인했습니다.
- **문항의 처리 흐름**:
1. 문항 등록
2. 세트로 묶기
3. 문항에 새끼 문항 추가
4. 수정 및 삭제 가능
- 이러한 흐름에 따라 **문항**과 **새끼 문항**은 별도의 애그리거트로 설계되었습니다.
---
- **개념 태그가 문항을 알 필요가 있는가?**
```java
public class ConceptTag {
private Set<Problem> problems = new HashSet<>();
}
```
- 특정 개념 태그로 문항을 필터링하는 상황에서는 유용할 수 있지만, 개념 태그에 연결된 문항이 많아질 경우 **(예를 들어 수 만건 정도) 모든 문항을 한 번에 로드해야 하는 성능 문제**가 발생합니다.
- 페이지네이션으로 문항의 로드를 제한한다고 해도, `problems` 필드를 읽는 순간 결국엔 똑같이 많은 데이터를 로드하고 어플리케이션 내에서 필터링하게 됩니다.
- **결론**: 개념 태그는 문항의 정보를 직접 참조하지 않도록 설계.
- 문항은 자신에게 달린 개념 태그를 반드시 알아야 하므로, **문항에서 개념 태그를 조회**하는 단방향 연관관계를 설계했습니다.
- **객체 참조 vs ID 참조**:
- **객체 참조**:
```java
public class Problem { …
```
> Feature/#21 문항, 새끼문항, 개념태그 엔티티 구현

- src/main/java/com/moplus/moplus_server/domain/v0/DetailResultApplication/service/DetailResultApplicationService.java
- src/main/java/com/moplus/moplus_server/domain/v0/practiceTest/repository/ProblemForTestRepository.java
- src/main/java/com/moplus/moplus_server/domain/v0/practiceTest/service/admin/PracticeTestAdminService.java
- src/main/java/com/moplus/moplus_server/domain/v0/practiceTest/service/admin/ProblemImageUploadService.java
- src/main/java/com/moplus/moplus_server/domain/v0/practiceTest/service/client/ProblemService.java
- src/test/java/com/moplus/moplus_server/domain/practiceTest/service/client/PracticeTestServiceTest.java
- close #24 
- ProblemRepository 빈 이름이 겹쳐 충돌이 발생하는 문제를 해결했습니다.
> [fix/#24] problem repository bean 이름 겹침 충돌 해결

- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/Problem.java
- src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetController.java
- src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
- src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSetConfirmStatus.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemReorderRequest.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemSetPostRequest.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemSetUpdateRequest.java
- src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetRepository.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetDeleteService.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetSaveService.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetUpdateService.java
- src/main/java/com/moplus/moplus_server/domain/publish/domain/Publish.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
- src/test/java/com/moplus/moplus_server/domain/problemset/ProblemSetServiceTest.java
- src/test/resources/insert-problemset.sql
- close #29 
- 다음과 같은 도메인 관계를 생각하며 구현했습니다.
* 문항은 여러 문항세트에 속할 수 있고, 문항 세트 또한 여러 개의 문항을 가지고 있습니다.
* 때문의 DDD 개발론의 ID참조를 통한 단방향 매핑을 통해 구현했습니다.
* String 리스트로 저장을 할까 생각했지만, 문항 Repository가 ProblemId를 기준으로 키값을 관리하기 때문에, ProblemId 리스트로 문항들을 관리하기로 결정했습니다.
* 아직 API를 구현해보지 않아서 그럴 수도 있지만, 날짜와 Id 참조를 통한 문항 세트만 존재하는 발행 테이블을 만들면 된다고 생각했습니다.
https://github.com/team-MoPlus/moplus_server/blob/ffa7cf32e1808386441c8ab9e05ab13ad5c957e3/src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetUpdateService.java#L38-L50
* 문항세트를 업데이트할 시, 요청으로 받은 문항 ID들이 실제 DB에 있는 값들인지 확인하는 로직을 추가했습니다.
https://github.com/team-MoPlus/moplus_server/blob/ffa7cf32e1808386441c8ab9e05ab13ad5c957e3/src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/Problem.java#L124-L133
* 문항세트를 "컨펌" 상태로 바꾸는 경우에 문항세트 …
> Feature/#29 문항 세트, 발행 도메인 및 문항세트 생성, 수정, 삭제, 컨펌 API 구현

- Dockerfile
- Dockerfile.prod
- docker-compose-dev.yml
- docker-compose-prod.yml
- src/main/resources/application.yml
- close #38
- 개발 및 운영 서버 url이 cors 설정에 적용되지 않았던 문제를 해결했습니다.
- 
-
> [hotfix/#38] cors url 추가

- src/main/java/com/moplus/moplus_server/global/security/handler/EmailPasswordSuccessHandler.java
- src/main/resources/application.yml
- src/test/java/com/moplus/moplus_server/domain/auth/controller/AuthControllerTest.java
- close #44 
- 로그인 시 jwt 전달 위치를 body로 변경하고 cors에 localhost:5173을 추가하였습니다.
- 
-
> [fix/#44] jwt 전달 위치 변경 및 cors 추가

- src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetSearchController.java
- src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSetGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSetSearchGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetRepository.java
- src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetGetService.java
- src/main/java/com/moplus/moplus_server/domain/publish/controller/PublishController.java
- src/main/java/com/moplus/moplus_server/domain/publish/domain/Publish.java
- src/main/java/com/moplus/moplus_server/domain/publish/dto/request/PublishPostRequest.java
- src/main/java/com/moplus/moplus_server/domain/publish/dto/response/PublishMonthGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/publish/dto/response/PublishProblemSetResponse.java
- src/main/java/com/moplus/moplus_server/domain/publish/repository/PublishRepository.java
- src/main/java/com/moplus/moplus_server/domain/publish/service/PublishDeleteService.java
- src/main/java/com/moplus/moplus_server/domain/publish/service/PublishGetService.java
- src/main/java/com/moplus/moplus_server/domain/publish/service/PublishSaveService.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
- src/test/java/com/moplus/moplus_server/domain/problemset/ProblemSetServiceTest.java
- src/test/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustomTest.java
- src/test/java/com/moplus/moplus_server/domain/publish/service/PublishServiceTest.java
- src/test/resources/insert-problem-set.sql
- src/test/resources/insert-problem-set2.sql
- close #42 
* 발행과 관련된 api들을 구현했습니다.
* 발행 생성 시 컨펌이 완료된 세트, 존재하는 세트, 삭제되지 않은 세트들만 발행되도록 구현했습니다.
* 발행 날짜는 발행하는 시점을 기준으로 다음날부터만 가능하도록 했습니다.
* 발행은 삭제하고, 다시 세트를 등록하는 플로우로 이해하고 수정은 구현하지 않고, 삭제 시 디비에서 바로 삭제되도록 했습니다.
* 문항세트 컨펌 시 유효하지 않은 문항이 포함되어 있다면, 해당 문항ID들을 에러메시지에 담아 출력해주었습니다.
* 문항세트 조회 시(개별 조회, 검색) 발행 유무와, 발행되었다면 발행날짜를 포함하여 조회되도록 수정했습니다.
> Feature/#42 발행 관련 api 추가

- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapperImpl.java
- src/main/java/com/moplus/moplus_server/domain/auth/controller/AuthController.java
- src/main/java/com/moplus/moplus_server/domain/auth/controller/AuthControllerDocs.java
- src/main/java/com/moplus/moplus_server/domain/auth/dto/request/AdminLoginRequest.java
- src/main/java/com/moplus/moplus_server/domain/auth/dto/response/AccessTokenResponse.java
- src/main/java/com/moplus/moplus_server/domain/auth/service/AuthService.java
- src/main/java/com/moplus/moplus_server/domain/concept/controller/ConceptTagController.java
- src/main/java/com/moplus/moplus_server/domain/concept/dto/response/ConceptTagResponse.java
- src/main/java/com/moplus/moplus_server/domain/member/controller/MemberController.java
- src/main/java/com/moplus/moplus_server/domain/problem/controller/PracticeTestTagController.java
- src/main/java/com/moplus/moplus_server/domain/problem/controller/ProblemController.java
- src/main/java/com/moplus/moplus_server/domain/problem/controller/ProblemSearchController.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/ProblemAdminId.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/request/ProblemPostRequest.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/request/ProblemUpdateRequest.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ChildProblemGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ConceptTagSearchResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/PracticeTestTagResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemSearchGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetController.java
- src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetSearchController.java
- src/main/java/com/moplus/moplus_server/domain/publish/controller/PublishController.java
- src/main/java/com/moplus/moplus_server/global/config/security/SecurityConfig.java
- src/main/java/com/moplus/moplus_server/global/error/GlobalExceptionHandler.java
- src/main/java/com/moplus/moplus_server/global/security/handler/EmailPasswordSuccessHandler.java
- src/main/java/com/moplus/moplus_server/global/security/utils/CookieUtil.java
- src/main/java/com/moplus/moplus_server/global/security/utils/JwtUtil.java
- src/test/java/com/moplus/moplus_server/domain/auth/controller/AuthControllerTest.java
- src/test/java/com/moplus/moplus_server/domain/auth/controller/RefreshTokenReissueTest.java
- close #48 
1.  jwt refresh 토큰으로 accessToken을 재발급 하는 reissue api를 추가하였습니다.
- 로그인이나 토큰 재발급 시 jwt refreshToken이 cookie에 담아서 전송됩니다.
- http-only, samesite, secure 설정이 되어 있습니다.
- http-only : XSS 공격 방지
- samesite, secure : CSRF 공격 방지
2. swagger ui를 같은 도메인 끼리 묶어 깔끔하게 수정하였습니다.
> Refactor/#48 jwt refresh 토큰 쿠키에 전송 및 swagger ui 변경

- src/main/java/com/moplus/moplus_server/domain/problem/controller/ImageUploadController.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/ProblemImageType.java
- src/main/java/com/moplus/moplus_server/domain/problem/repository/ProblemRepository.java
- src/main/java/com/moplus/moplus_server/domain/problem/service/ImageUploadService.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
- src/main/java/com/moplus/moplus_server/global/utils/s3/S3Util.java
> [feat/#50] presigned url 구현

- src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemThumbnailResponse.java
- src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
- src/main/java/com/moplus/moplus_server/domain/publish/controller/PublishController.java
- src/main/java/com/moplus/moplus_server/domain/publish/dto/request/PublishPostRequest.java
- src/test/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustomTest.java
- close #47 
- 추가된 문항 필드에 따라, 문항세트 검색시 문항타이틀, 문항메모 필드를 추가했습니다.
- Null값이 오면 안되는 필드에 대한 유효성검사를 추가했습니다.
> Feature/#47 문항세트 검색 시 문항타이틀, 문항메모 필드 추가

- src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetSearchController.java
- src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
- src/main/java/com/moplus/moplus_server/global/response/ResponseDto.java
- src/main/java/com/moplus/moplus_server/global/response/ResponseDtoAdvice.java
- src/test/java/com/moplus/moplus_server/domain/member/controller/MemberControllerTest.java
- src/test/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustomTest.java
- close #55
* 필드 없이 값만 body에 넣어 내려오는 응답들을 json형식으로 감싸주기 위해 어드바이스를 추가했습니다.
* ResponseBodyAdvice를 활용하여 모든 응답을 ResponseDto<T> 형식으로 감싸도록 설정했습니다.
* 기존 ErrorResponse 타입의 응답은 fail 함수로 변환해줍니다.
* 결과적으로 모든 성공 응답에 data필드가 추가되었고, 실패 응답은 동일한 형태입니다.
* 문항세트 검색 시 (목록용, 발행용) 개념태그 검색은 삭제했습니다.
* 문항세트 타이틀, 포함된 문항 타이틀로만 검색되도록 변경했습니다.
> Hotfix/#55 문항세트, 발행 문제 해결

- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapperImpl.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/Problem.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/ProblemAdminIdService.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemPostResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/service/ProblemSaveService.java
- src/main/java/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapper.java
- src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSummaryResponse.java
> [fix/#54] 문항 생성 오류 해결

- src/main/generated/com/moplus/moplus_server/domain/problem/domain/problem/QProblem.java
- src/main/generated/com/moplus/moplus_server/domain/problem/domain/problem/QRecommendedTime.java
- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapperImpl.java
- src/main/java/com/moplus/moplus_server/domain/problem/controller/ProblemSearchController.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/Problem.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/RecommendedTime.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/request/ProblemUpdateRequest.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/repository/ProblemSearchRepositoryCustom.java
- src/main/java/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapper.java
- src/test/java/com/moplus/moplus_server/domain/problem/domain/problem/ProblemCustomIdServiceTest.java
- src/test/java/com/moplus/moplus_server/domain/problem/service/ProblemUpdateServiceTest.java
- src/test/resources/concept-tag.sql
- src/test/resources/insert-problem.sql
- src/test/resources/insert-problem2.sql
- src/test/resources/practice-test-tag.sql
> [fix/#54] 문항 추천 시간 추가

- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/PresignedUrlResponse.java
- src/main/java/com/moplus/moplus_server/global/config/swagger/SwaggerConfig.java
- src/main/java/com/moplus/moplus_server/global/response/ResponseDto.java
- src/main/java/com/moplus/moplus_server/global/response/ResponseDtoAdvice.java
- src/test/java/com/moplus/moplus_server/domain/member/controller/MemberControllerTest.java
- close #57 
- ResponseAdvice와 Swagger를 함께 사용할 때, 스키마에 공통 응답이 반영되지 않던 오류를 해결했습니다.
- springdoc의 OperationCustomizer를 빈으로 등록하여 스키마 Json형식을 직접 수정했습니다.
- ResponseAdvice가 봉투패턴으로 감싸주는 것은 String을 제외한 객체들입니다.
- String은 MappingJackson2HttpMessageConverter 클래스로 변환되지 않고, 그대로 body에 들어가기 때문에, 만약 String으로 응답을 해야하는 api는 별도의 dto를 적용해주어야 합니다.
> [feat/#57] 공통응답 스웨거 스키마 반영

- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ChildProblemMapperImpl.java
- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapperImpl.java
- src/main/generated/com/moplus/moplus_server/domain/v0/TestResult/entity/QIncorrectProblem.java
- src/main/generated/com/moplus/moplus_server/domain/v0/practiceTest/domain/QProblemImageForTest.java
- src/main/java/com/moplus/moplus_server/domain/problem/controller/ImageUploadController.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/Answer.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/childProblem/ChildProblem.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/AnswerType.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/request/ChildProblemPostRequest.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/request/ChildProblemUpdateRequest.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/request/ProblemUpdateRequest.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ChildProblemGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemSearchGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/repository/ProblemSearchRepositoryCustom.java
- src/main/java/com/moplus/moplus_server/domain/problem/service/ImageUploadService.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemReorderRequest.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemSetPostRequest.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemSetUpdateRequest.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSetGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSetSearchGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSummaryResponse.java
- src/test/java/com/moplus/moplus_server/domain/problem/repository/ProblemSearchRepositoryCustomTest.java
> Hotfix/#54 문항 변경사항 반영

- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ChildProblemMapperImpl.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/request/ChildProblemUpdateRequest.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/PresignedUrlResponse.java
- src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemSearchGetResponse.java
- src/main/java/com/moplus/moplus_server/global/response/IdResponse.java
> [fix/#54] 문항 변경 사항 반영

- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ChildProblemMapperImpl.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/Answer.java
- src/main/java/com/moplus/moplus_server/domain/problem/service/mapper/ChildProblemMapper.java
- src/test/java/com/moplus/moplus_server/domain/auth/controller/AuthControllerTest.java
- src/test/java/com/moplus/moplus_server/domain/problem/service/ProblemUpdateServiceTest.java
- src/test/resources/insert-problem.sql
- src/test/resources/insert-problem2.sql
> [fix/#54] 문항 응답 필수값 변경

- src/main/java/com/moplus/moplus_server/domain/problem/domain/childProblem/ChildProblem.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/Problem.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/RecommendedTime.java
- src/main/java/com/moplus/moplus_server/domain/problem/repository/converter/StringListConverter.java
> [fix/#54] 문항 추천시간 0으로 초기화 변경

- src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
- src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetRepository.java
- src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetGetService.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetUpdateService.java
- src/main/java/com/moplus/moplus_server/domain/publish/domain/Publish.java
- src/main/java/com/moplus/moplus_server/domain/publish/dto/response/PublishMonthGetResponse.java
- src/main/java/com/moplus/moplus_server/domain/publish/service/PublishSaveService.java
- src/main/java/com/moplus/moplus_server/global/error/ErrorResponse.java
- src/main/java/com/moplus/moplus_server/global/error/GlobalExceptionHandler.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ProblemSetToggleException.java
- src/test/java/com/moplus/moplus_server/domain/problemset/ProblemSetServiceTest.java
- src/test/java/com/moplus/moplus_server/domain/publish/service/PublishServiceTest.java
- resolved: #77 
* 발행 조회 시 연월일을 전부 내려주도록 변경했습니다.
* 당일에 발행이 가능하도록 변경했습니다.
* 삭제된 문항세트 체크가 이루어지지 않고 있었어서, 삭제된 문항세트는 조회, 검색, 수정이 불가능하게 변경했습니다.
* 빈 문항세트에 대해서 컨펌이 안되도록 변경했습니다.
* 문항세트 컨펌 실패 시, 유효성 검사에 통과하지 못한 문항들의 커스텀ID를 응답 body에 추가했습니다. 이를 위해 ProblemSetToggleException이라는 추가 에러클래스를 생성했습니다.
* 발행 실패 시 컨펌되지 않은 문항세트라 실패했는지, 삭제된 문항세트라 실패했는지에 대핸 에러 메시지를 세분화했습니다.
> Fix/#77 발행 이슈 해결

- src/main/java/com/moplus/moplus_server/client/submit/controller/ClientGetController.java
- src/main/java/com/moplus/moplus_server/client/submit/controller/ClientSubmitController.java
- src/main/java/com/moplus/moplus_server/client/submit/controller/CommentaryGetController.java
- src/main/java/com/moplus/moplus_server/client/submit/controller/ProblemGetController.java
- src/main/java/com/moplus/moplus_server/client/submit/domain/ChildProblemSubmit.java
- src/main/java/com/moplus/moplus_server/client/submit/domain/ChildProblemSubmitStatus.java
- src/main/java/com/moplus/moplus_server/client/submit/domain/ProblemSubmit.java
- src/main/java/com/moplus/moplus_server/client/submit/domain/ProblemSubmitStatus.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/request/ChildProblemSubmitCreateRequest.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/request/ChildProblemSubmitUpdateIncorrectRequest.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/request/ChildProblemSubmitUpdateRequest.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/request/ProblemSubmitCreateRequest.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/request/ProblemSubmitUpdateRequest.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/response/AllProblemGetResponse.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/response/ChildProblemClientGetResponse.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/response/ChildProblemDetailResponse.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/response/CommentaryGetResponse.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/response/DayProgress.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/response/PrescriptionResponse.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/response/ProblemClientGetResponse.java
- src/main/java/com/moplus/moplus_server/client/submit/dto/response/ProblemDetailResponse.java
- src/main/java/com/moplus/moplus_server/client/submit/repository/ChildProblemSubmitRepository.java
- src/main/java/com/moplus/moplus_server/client/submit/repository/ProblemSubmitRepository.java
- src/main/java/com/moplus/moplus_server/client/submit/service/ClientGetService.java
- src/main/java/com/moplus/moplus_server/client/submit/service/ClientSubmitService.java
- src/main/java/com/moplus/moplus_server/client/submit/service/CommentaryGetService.java
- src/main/java/com/moplus/moplus_server/client/submit/service/ProblemsGetService.java
- src/main/java/com/moplus/moplus_server/domain/problem/repository/ProblemRepository.java
- src/main/java/com/moplus/moplus_server/domain/publish/repository/PublishRepository.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
- resolved: #94 
- 전체문제 조회
- 바로 풀러가기 : 문항 제출 생성(진행중으로)
- 단계별로 풀러가기 : 새끼문항 제출 생성(시작전으로)
- 문항 제출 상태 변경
- 새끼문항 제출 상테 변경
- 새끼문항 스킵(틀림 처리)
- 해설 조회
- 사용자 문항 조회
- 사용자 새끼문항 조회
- 새끼문항에 '시작전' 상태가 추가되었습니다.
- 프론트엔드 개발자와 논의 한 후, 단계별로 풀러가기를 눌렀을 떄 새끼문항제출 데이터들이 생성되는 것이 자연스럽다고 생각했습니다.
- 현재 로그인 기능이 없어서, 모든 api의 memberId는 1을 기준으로 구현되었습니다.
- 추후 로그인 기능 추가 후, 일괄 변경하겠습니다.
> Feature/#94 사용자 제출 관련 api 구현

- src/main/generated/com/moplus/moplus_server/statistic/Problem/domain/QChildProblemStatistic.java
- src/main/generated/com/moplus/moplus_server/statistic/Problem/domain/QCountStatistic.java
- src/main/generated/com/moplus/moplus_server/statistic/Problem/domain/QProblemSetStatistic.java
- src/main/generated/com/moplus/moplus_server/statistic/Problem/domain/QProblemStatistic.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/domain/ChildProblemStatistic.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/domain/CountStatistic.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/domain/CountUpper.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/domain/ProblemSetStatistic.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/domain/ProblemStatistic.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/domain/StatisticCounter.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/domain/StatisticEntityTarget.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/domain/StatisticFieldType.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/repository/ChildProblemStatisticRepository.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/repository/ProblemSetStatisticRepository.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/repository/ProblemStatisticRepository.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/service/CountStatisticsUpdateService.java
- src/test/java/com/moplus/moplus_server/statistic/Problem/service/CountStatisticsUpdateServiceTest.java
- resolved: #92 
- 문항, 새끼문항, 세트에 대한 조회수, 풀이수 통계를 위한 도메인 설계를 진행하였습니다.
- 각 도메인에 대해서 조회수, 풀이수를 업데이트를 하는 행위는 모두 같았습니다.
- 업데이트를 해야하는 필드도 같았고 수행하는 로직의 규칙도 같았습니다.
- 공통 로직임에도 불구하고 각 통계 도메인별로 똑같은 행위를 하는 서비스 구현체가 각각 생기는 것은 유지보수 측면에서 좋아보이지 않았습니다.
- 예시) ProblemStatisticUpdateService, ChildProblemStatisticUpdateService, ProblemSetStatisticUpdateService
- 하나의 서비스에서 여러 instance 종류에 상관없이 공통 로직을 수행시키기 위해 아래와 같은 2가지 구조를 고민했습니다.
- 다형성을 구현하기 위해 상속을 고려했으나, DB의 테이블 구조가 상속을 지원하지 않고 이를 하나의 테이블로 구현하거나 공통 부분과 하위 부분을 두 개로 나누어 type을 통해 연결하는 방식이 있었습니다.
- 하지만 이러한 방식은 확장성에 제약이 있을 것 같았고, 조회수와 풀이수 같은 공통적인 통계가 문항, 새끼문항, 세트 등 다양한 도메인의 내용이 통계라는 한 공통 상위 테이블에 섞여 저장되면 조회 성능에도 문제가 될 수 있었습니다.
- 각 도메인이 CountStatistic를 내부로 가지고 있는 합성을 선택하고 StatisticCounter 인터페이스를 구현하게하여 다형성을 구현했습니다.
- 통계 서비스는 PROBLEM, PROBLEM_SET, CHILD_PROBLEM으로 …
> Feature/#92 조회수, 풀이수 통계 업데이트 공통 서비스 구현

- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ChildProblemMapperImpl.java
- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapperImpl.java
- src/main/java/com/moplus/moplus_server/admin/publish/service/PublishGetService.java
- src/main/java/com/moplus/moplus_server/client/homefeed/controller/HomeFeedController.java
- src/main/java/com/moplus/moplus_server/client/homefeed/dto/response/HomeFeedResponse.java
- src/main/java/com/moplus/moplus_server/client/homefeed/service/HomeFeedFacadeService.java
- src/main/java/com/moplus/moplus_server/client/submit/repository/ProblemSubmitRepository.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetGetService.java
- src/main/java/com/moplus/moplus_server/statistic/Problem/service/CountStatisticsGetService.java
- resolved: #98 
- 홈피드에서는 이번주 진척도와 이번주에 발행된 (월,화,수,목,금)에 대한 문제 세트의 첫번째 문항을 보여주고 있어요
- 이번 pr에서는 이번주에 발행된 문제세트 정보를 내려주는 로직만 추가했어요
> [feat/98] 이번주 문제 영역 조회

- src/main/java/com/moplus/moplus_server/client/homefeed/dto/response/HomeFeedResponse.java
- src/main/java/com/moplus/moplus_server/client/homefeed/service/HomeFeedFacadeService.java
- src/main/java/com/moplus/moplus_server/client/submit/domain/ProgressStatus.java
- src/main/java/com/moplus/moplus_server/client/submit/service/ProblemSubmitGetService.java
- resolved: #100 
- 홈 피드에 이번주 진척도에 대한 데이터가 같이 내려가요
- 데이터 형식은 아래와 같아요
```json
{
"data": {
"dailyProgresses": [
{
"date": "2025-03-24",
"progressStatus": "NOT_STARTED"
},
{
"date": "2025-03-25",
"progressStatus": "NOT_STARTED"
},
{
"date": "2025-03-26",
"progressStatus": "NOT_STARTED"
},
{
"date": "2025-03-27",
"progressStatus": "NOT_STARTED"
},
{
"date": "2025-03-28",
"progressStatus": "NOT_STARTED"
}
],
"problemSets": [
{
"date": "2025-03-24",
"problemSetId": null,
"title": null,
"submitCount": null,
"problemHomeFeedResponse": null
},
{
"date": "2025-03-25",
"problemSetId": null,
"title": null,
"submitCount": null,
"problemHomeFeedResponse": null
},
{
"date": "2025-03-26",
"problemSetId": null,
"title": null,
"submitCount": null,
"problemHomeFeedResponse": null
},
{
"date": "2025-03-27", …
```
> Feature/#100 이번주 진척도 표시

- src/main/java/com/moplus/moplus_server/client/problem/controller/ProblemGetController.java
- src/main/java/com/moplus/moplus_server/client/problem/dto/response/ProblemThumbnailResponse.java
- src/main/java/com/moplus/moplus_server/client/problem/service/ProblemsGetService.java
- src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
- resolved: #104 
- 바로 풀어보기/단계별로 풀어보기 화면에서 필요한 문항 조회를 구현했어요.
- 문제 풀러가기 뷰에서 조회한 발행id와 문항번호를 통해서 조회돼요.
- 데이터 형식은 다음과 같아요.
```json
{
"data": {
"number": 1,
"imageUrl": "https://s3-moplus.s3.ap-northeast-2.amazonaws.com/problems/1/main-problem/d989f0a8-5249-4526-8602-b41a5fdcfcc7.jpg",
"recommendedMinute": 2,
"recommendedSecond": 40
}
}
```
> [feat/#104] 문항 썸네일 조회 api

- src/main/java/com/moplus/moplus_server/client/submit/controller/ClientSubmitController.java
- src/main/java/com/moplus/moplus_server/client/submit/controller/CommentaryGetController.java
- src/main/java/com/moplus/moplus_server/client/submit/service/ClientSubmitService.java
- src/main/java/com/moplus/moplus_server/client/submit/service/CommentaryGetService.java
- resolved: #106 
- 해설을 조회할 때, 새끼문항의 제출 상태를 조회하는 로직이 있어요.
- 문제는 새끼문항을 제출하지 않았을 때는 해설이 조회되지 않고 있었어요.
- 문항의 제출 여부만을 체크한 후, 해설을 내려주는 로직으루 수정했어요.
- 데이터 형식은 아래와 같아요.
```json
{
"data": {
"problemNumber": 1,
"answer": "4",
"mainAnalysisImageUrl": "https://s3-moplus.s3.ap-northeast-2.amazonaws.com/problems/1/main-analysis/fea38b73-0669-4224-b90d-ac03782d5964.jpg",
"mainHandwritingExplanationImageUrl": "https://s3-moplus.s3.ap-northeast-2.amazonaws.com/problems/1/main-handwriting-explanation/fe0dee8b-0470-4b02-ae59-669c7518c989.jpg",
"readingTipImageUrl": "https://s3-moplus.s3.ap-northeast-2.amazonaws.com/problems/1/reading-tip/8fc723ce-1ae6-4c08-ab31-c07d4a86afd0.jpg",
"seniorTipImageUrl": "https://s3-moplus.s3.ap-northeast-2.amazonaws.com/problems/1/senior-tip/d6046f67-39be-4261-82ab-4ebbf9ca9c68 …
```
> Fix/#106 해설조회 로직 수정

- src/main/java/com/moplus/moplus_server/client/problem/controller/ProblemGetController.java
- src/main/java/com/moplus/moplus_server/client/problem/dto/response/ChildProblemsClientGetResponse.java
- src/main/java/com/moplus/moplus_server/client/problem/service/ProblemsGetService.java
- resolved: #111 
- 단계별로 풀어보기에 진입한 후, 새끼문항들을 조회하기 위한 ID들을 조회해요.
- 메인문항 이미지 보기 기능을 위해 메인문항 이미지도 포함했어요.
- 응답 데이터는 아래와 같아요.
```json
{
"data": {
"mainProblemImageUrl": "https://s3-moplus.s3.ap-northeast-2.amazonaws.com/problems/1/main-problem/d989f0a8-5249-4526-8602-b41a5fdcfcc7.jpg",
"childProblemIds": [
9,
10
]
}
}
```
> [feat/#111] 문항에 포함된 새끼문항ID들 조회

- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ChildProblemMapperImpl.java
- src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapperImpl.java
- src/main/generated/com/moplus/moplus_server/domain/problemset/domain/QProblemSet.java
- src/main/java/com/moplus/moplus_server/admin/publish/domain/Publish.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/childProblem/ChildProblem.java
- src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/Problem.java
- src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
- src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetRepository.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetDeleteService.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetGetService.java
- src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetUpdateService.java
- hibernate 6에 추가된 @SoftDelete를 problem, problemset, publish, childProblem에 적용했습니다
> [hotfix] softdelete hibernate 6로 교체

- src/main/java/com/moplus/moplus_server/client/submit/dto/response/DayProgress.java
- 월별 조회시 날짜별 진행도 결정 로직을 수정했습니다.
- 해당 발행 날짜에 대해 모든 문항의 제출 상태가 시작전 -> 미완료
- 모든 문항이 맞음/틀림/다시맞춤 -> 완료
- 나머지 경우 -> 진행중
> [hotfix] 월별 조회시 날짜별 진행도 결정 로직 수정
